spring:
  cloud:
    discovery:
      enabled: false

eureka:
  instance:
    hostname: localhost
    username: netflix
    password: eureka

  client:
    service-url:
      defaultZone: http://${eureka.instance.username}:${eureka.instance.password}@${eureka.instance.hostname}:8761/eureka/